### ISSUE TITLE
Project maintenance

### ISSUE THREAD

**Issue by vegu** [20c/vaping#108]
- replace travis with github actions
- switch to pyproject.toml and poetry
- flake8
- isort
- move code to /src

**Comment by AndreCimander** [comment]
Might I recommend [Black](https://github.com/psf/black) for automatic code formatting? :-)

Started using Black about one year ago and it really helps with getting merge requests up to standard in seconds.

And thanks for this project! :-)

**Comment by AndreCimander** [comment]
@grizz oh, alright then, awesome! Just took a quick glance and didn't see it :see_no_evil: 

Have a great Saturday!
