### ISSUE TITLE
new ping type, MTR

### ISSUE THREAD

**Issue by telsin** [20c/vaping#11]
To go with https://github.com/20c/graphsrv/issues/9

Should either use MTR or do an MTR like single ping of each hop once per second and report each hops IP, DNS (optional), RTT (or -null- for no response/loss).

**Comment by rrodstein** [comment]
Greetings, 

Has this enhancement along with 20c/graphsrv#9 been accepted? 

Have ya'll had any luck testing MTR/vaping in your lab? If yes, could you please share the setup so we can test, and provide feedback?

We are also looking for a MTR visualization option that would answer the "where is the problem" question.

Respectfully,

**Comment by vegu** [comment]
It's accepted, but currently no ETA on official implementation.

Personally i have not yet had time to test a MTR graph. I feel that implementing it on the vaping side should be quick.

The visualization in graphsrv might be a different story, although a bar graph is already supported, so maybe able to piggy back on that.

If interest in this is picking up, i wouldn't mind having a go at it in the near future as time permits.

**Comment by rrodstein** [comment]
We really like vaping, great project!

We would welcome the opportunity to assist with testing/tuning MTR/graphing. 

Having the "where is the problem" part of the equation in vaping would valuable.

**Comment by vegu** [comment]
We are currently investigating a switch to a third part library for the actual rendering of the graphs in https://github.com/20c/graphsrv/issues/25, as that would free up a lot of resources on our end allowing us to implement new graphs like this quicker.

**Comment by vegu** [comment]
A first iteration of an MTR graph has been released with 0.6.0 - instructions on how to setup can be found at: http://vaping.readthedocs.io/en/latest/examples/#mtr

Note that i'd consider this experimental at this point, @telsin already had plenty of improvement suggestions, but we would love to hear everyone's thoughts - so leaving this ticket open for now.
