### ISSUE TITLE
show percentage packet loss

### ISSUE THREAD

**Issue by aspiers** [20c/vaping#14]
It would be nice if packet loss was also displayed as a percentage (i.e. in addition to the loss counter, not in lieu of it).  Of course when the sliding window is only 10 pings this is not too useful, but if it's a bigger number (other than 100!) then it becomes useful.

**Comment by vegu** [comment]
I agree, this could probably sufficiently be done by adding it as a suffix to loss / count

so it would show "loss / count (loss%)" or something to that effect. The data is already provided by vaping so this would need to be implemented in graphsrv, going to make a ticket there for it as well.

**Comment by vegu** [comment]
fixed in graphsrv 1.1.3

**Comment by aspiers** [comment]
Looks great, thanks!!
