### ISSUE TITLE
Display more than 3 graphs for packet loss

### ISSUE THREAD

**Issue by CTV-ByImmo** [20c/vaping#143]
Hi,

Is it possible to display more than 3 small graphs ? These are the only one to display packet loss. My main graph has 6 destinations IP.

![2021-11-08_11h29_05](https://user-images.githubusercontent.com/64533932/140726422-d6176973-76a6-4e69-acfa-fa606693c3e9.png)

**Comment by vegu** [comment]
hi @CTV-ByImmo 

You can customize layouts, in your case you will want to update the `detail` layout

https://graphsrv.readthedocs.io/en/latest/custom/#layout

Basically copy https://github.com/20c/graphsrv/blob/master/graphsrv/etc/layouts.yaml to a new location and edit it, then set your `apps.graphsrv.layout_config_file` in your config to point to your new layout file.

**Comment by vegu** [comment]
@CTV-ByImmo closing this issue, please re-open if you still need assistance
