### ISSUE TITLE
Docs/Examples needed for simple configurations

### ISSUE THREAD

**Issue by MarkOnDuty** [20c/vaping#148]
Compared to SmokePing, Vaping was a piece of cake to get up, running, and watching the hosts I'm interested in. Thanks for that.

The configuration documentation and examples leave me hanging on the first couple of things I want to do:

   * messing with the layout
   * keeping more than 20 minutes of history
   * how does one get back from the detail layout?

Yes, the Vaping docs point one to the graphsrv docs, which do have an example of a 2x2 grid, but where does that fit into the Vaping configuration, or is it in a separate YML file altogether? I would be stoked if I could get a 1x3 grid for the index layout.

For the life of me, I can't figure out how to modify the standalone latency example to display more than 20 minutes of history. I'd like a couple of hours, at least.

I let out a whoop of joy when I accidentally discovered the detail layout, but switched to frustrated grumbles when I couldn't figure out how to get back to the index layout without editing the URL.

**Comment by vegu** [comment]
Hi @MarkOnDuty sorry for the delayed response, just now getting back into things

I completely agree that things like layout configuration needs to be documented better within the vaping docs itself.

Copy https://github.com/20c/graphsrv/blob/master/graphsrv/etc/layouts.yaml to a new location and edit it, then set your apps.graphsrv.layout_config_file in your config to point to your new layout file.

You can update the overview layout in there as well as the detail layout.

> how does one get back from the detail layout?

Other than going back in the browser history, there currently is none, which seems like an oversight

Alas our cycles this month are really limited

**Comment by vegu** [comment]
To keep more history up the limit parameter in the data config

```
    data:
      - type: fping
        handlers:
          - type: index
            index: host
          - type: store
            container: list
            limit: 500
```

Note that this has a tendency to get laggy rather qick, and if you need a long term history storage of the data the better option for now is to also output to a timeseries db, with the caveat that history storied in a timeseries db is currently not accessible from the UI.

**Comment by MarkOnDuty** [comment]
> To keep more history up the limit parameter in the data config

Nice. I'm giving this a go now.

As for the timeseries db... Would it make sense, or be possible, to just throw the data coming from Vaping into Grafana or a similar tool? That way the front-end isn't your problem. Grafana's interface is pretty decent, from my experience.

**Comment by vegu** [comment]
I am not familiar with Grafana, will need to take a look - generally speaking as long as Grafana exposes an API or database to post to extending a vaping plugin that outputs to that shouldn't be too difficult.
