### ISSUE TITLE
Add better documentation for new users

### ISSUE THREAD

**Issue by slhck** [20c/vaping#158]
Coming in as a completely new user who was looking for a simple tool to traceroute/ping a few hosts, I was a bit confused by the documentation.

Here are my thoughts, in the hope that these comments can help improve the discoverability/accessibility of this (very nice) tool.

Happy to provide a PR but I wanted to check with you first, and I admit I am not sure how exactly everything works under the hood.

---

> Vaping was started after years of frustration …

The `README.md` does not really mention **what the tool does** except for saying that it is an alternative to smokeping. Now, granted, many people may know this, but if instead the REAMDE described what the tool *actually* did, it would probably make it more accessible for users just searching for a tool to do distributed ping on a schedule, with graphs, etc.

Also, whether or not there was frustration with other tools is very likely not so relevant for new users, as is the fact that asyncio is used in the background.

→ Briefly explain the features in a small list and explain why it's better than other tools

---

> Note, you will need a compiler and python development libraries for some components.

For which components? How do I know if I need them? Also, the example code shown below ("On CentOS/RHEL") seems to be the solution for only one type of distro —  what about others? (The quick start guide has examples for Ubuntu, for instance.)

→ Clarify when this is needed and add instructions for other common distros.

---

> Starts a vaping process, by default …

This seems to be a description of the usage, but simply running `vaping start`  tells me:

> ValueError: no config specified, please use specify a home directory

Apart from the grammatical error ("please use specify"), this is already quite confusing. The usage does not show `--home` as a required option. What does "home" stand for? Is it not `$HOME`?

→ I think that at this point the user should already be given an introduction into config files/homes.

---

The link to the documentation just brings me to the same page, albeit in readthedocs format. But how do I use this tool?

→ Add a direct link to the quick start guide to the README

---

In the quickstart guide:

> The example config file (from examples/standalone_dns) uses both vodka and graphsrv plugins, so those will need to be installed with

This has me confused again. Where is `examples/standalone_dns`? (Only later in the docs it tells me to clone the Git repo and find the example there.)

What is `vodka` and `graphsrv` … and why are they not installed directly when this is the most simple example?

→ Give the user an introduction on configs ("Config files are .yml files …") and tell the user to download the Git repo earlier on.

> just start vaping with

At this point the user still does not know what the example will actually do. Ping some servers? Which ones? At which interval?

→ Explain the intent of the example config.

**Comment by grizz** [comment]
@slhck all of that makes sense, a PR would be great, thanks!

**Comment by slhck** [comment]
Will do! Could you perhaps help out with those?

> Briefly explain the features in a small list

I think you will be in the best position to write down some :slightly_smiling_face: 

> you will need a compiler and python development libraries for some components

Which components?

**Comment by vegu** [comment]
hi @slhck, thanks for the contribution

> Briefly explain the features in a small list 

1. real-time latency graphing viewable in the browser
2. line and smokestack graphs
3. containerized and easy to setup and configure
4. support for time-series databases
5. plugin based design to allow integration with other services
6. supports distributed setups through message queue

> you will need a compiler and python development libraries for some components

For distributed setups that use `zeromq` to communicate `pip install` will need a compiler.

`rrd` support also needs a compiler available.

However, this is taken care off by the containerized approach, and not something people should have to worry about much anymore.

I am thinking we can just drop this note and encourage people to run vaping through the container.
