### ISSUE TITLE
OSError: config file not found in examples/standalone_dns

### ISSUE THREAD

**Issue by grizz** [20c/vaping#170]
Moved to a new issue since I lost in the closed one.

_Originally posted by @athompson-merlin in https://github.com/20c/vaping/issues/123#issuecomment-1462601713_

Err... I'm getting the same problem with munge==1.2.1 on a fresh install today, on Alma Linux 8 (an EL8 rebuild) with system-python 3.6.8.  

The `pip install` commands from the quickstart appear to have installed munge v1.2.1 which, according to strace(8), never _attempts_ to open the config file.  I don't know why 1.2.1 got installed instead of 1.2.0 as specified in the deps file.

Munge v1.2.0 also works fine, which is bizarre... I'm looking at the commits between munge 1.2.0 and 1.2.1, and there's nothing in there that should make any difference, unless the problem is in the downstream module "click" v8?

**Comment by grizz** [comment]
@athompson-merlin odd, do you have pyyaml installed?

It looks like munge and vaping both need updated releases.

**Comment by athompson-merlin** [comment]
> @athompson-merlin odd, do you have pyyaml installed?
> It looks like munge and vaping both need updated releases.

i'm sorry, I can't tell you - I got it running long enough to realize this tool isn't quite what I wanted and then deleted the entire VM.  (Right now, I'm explicitly looking for tools are that simple point-product solutions, _not_ swiss army knives that can do anything.  We're so understaffed at the moment, that ease of setup and ease of maintenance trump almost all other considerations.)

**Comment by grizz** [comment]
No worries, good luck! :)
