### ISSUE TITLE
limit of 3 per-host graphs

### ISSUE THREAD

**Issue by aspiers** [20c/vaping#18]
When I click on a probe group in the web UI, I reach a URL like http://localhost:7021/view/detail/latency.my_probe_group/ where it shows one big graph with latency of all hosts on it, and then underneath 3 smaller graphs, one for each host in the group, where I can see more detail like historical packet loss.  However if there are more than 3 hosts in the group, only 3 are displayed and I can't see detail for the others.  This layout should be configurable somehow.

**Comment by vegu** [comment]
Layout is configurable, please refer to the graphsrv documentation on how to do that for now, we may extend the vaping docs with some examples as well at some point - maybe some common layout configurations or something to that effect.

**How to configure graphsrv layouts:** http://graphsrv.readthedocs.io/en/latest/custom/

I recommend you take the default layout and copy it to get started: 

**Default layout:** https://github.com/20c/graphsrv/blob/master/graphsrv/etc/layouts.yaml

**Comment by vegu** [comment]
Oh, as i don't think many people have played around with the custom layout configurations at this point, i'd appreciate your feedback if you decide to do so, either here or at the graphsrv repo! Thanks  :)

**Comment by aspiers** [comment]
Thanks a lot for the quick response! Great to hear that graphsrv already has this flexibility.  Although even with this new knowledge it's still not clear to me how the graphsrv layout yaml is supposed to be integrated into vaping - I can't see that documented anywhere, and the vaping docs don't even mention graphsrv once.  I guess that's what #19 will tackle, but until that's resolved I'm a bit stuck on this.

**Comment by vegu** [comment]
1. make a copy of the layout.yaml that i linked above 
2. in the vaping config file locate the graphsrv application (should be plugins.vodka.apps.graphsrv if i recall correctly) 
3. add a key called 'layout_config_file' and set it's value to the path of the layout.yaml file you copied
4. restart vaping

Now whenever you edit your copy of the layout file, changes should appear immediately when doing a browser refresh.

**Comment by aspiers** [comment]
That was the missing piece, thanks!
