### ISSUE TITLE
UserWarning: Unknown distribution option: 'test_requires'

### ISSUE THREAD

**Issue by Gunni** [20c/vaping#21]
# pip3 install vaping
	Collecting vaping
	  Using cached vaping-0.3.0.tar.gz
		Complete output from command python setup.py egg_info:
		/usr/lib64/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'test_requires'
		  warnings.warn(msg)
		error in vaping setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected ',' or end-of-list in whichcraft==0.4.0 ; python_version<'3.3' at  ; python_version<'3.3'

		----------------------------------------
	Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-v0pduzzd/vaping/

> 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers

**Comment by vegu** [comment]
sounds like pip / setuptools needs to be updated 

pip install pip -U
pip install setuptools -U

then try again

**Comment by Gunni** [comment]
You were right, as soon as i ran the second command it started working, thanks!
