### ISSUE TITLE
Python3 complains about bytes-like object in fping.py

### ISSUE THREAD

**Issue by catmeme** [20c/vaping#29]
### Steps to reproduce:

1. Create a new virtualenv, and install `vaping` and dependencies for the example

```
virtualenv -p /usr/bin/python3 venv && ln -s venv/bin/activate && source activate
pip install vaping vodka graphsrv
wget https://github.com/20c/vaping/blob/master/examples/standalone_dns/config.yml
vaping start --home=. --debug
```

### Result

```
root b'' fping.py:70
root failed to get data a bytes-like object is required, not 'str' fping.py:101
root b'' fping.py:70
root failed to get data a bytes-like object is required, not 'str' fping.py:101
...
```

### Expected Result

```
root 4.2.2.1        : 10.36 9.59 9.66 9.02 9.33 9.75 10.19 10.29 10.38 10.09
 fping.py:70
root 208.67.222.222 : 6.54 7.25 6.71 6.03 6.33 6.66 5.51 5.94 5.90 6.66
 fping.py:70
root 8.8.8.8        : 6.26 7.91 5.85 5.39 5.39 5.95 6.44 5.56 5.98 5.80
 fping.py:70
...
```

### Additional Information

Creating the virtualenv with Python2, the expected result happens.

**Comment by vegu** [comment]
thanks for the report, managed to reproduce, tagging as bug

**Comment by nathaniel-mahieu** [comment]
Ran into this on ubuntu 16.01

**Comment by ludmata** [comment]
It still affects ubuntu 16.04 - I have checked your commit: https://github.com/20c/vaping/commit/0277a774b331d07cb24a1f4893cb75819ad12c7f
and that line line = line.decode("utf-8") was missing from latest version. I have added it and now it works fine.
