### ISSUE TITLE
vaping running but Example Standalone Latency page shows no data

### ISSUE THREAD

**Issue by rrodstein** [20c/vaping#32]
Hi, thank you in advance for your support! 
I've got vaping running on ubuntu 16.04 using a bridged network on virtual box via:
vaping start --home=/home/roy/vaping/examples/standalone_dns/ --debug
I'm able to access the http://the_vms_ip:7021 page, but there is no data, i.e. the charts are visible but without data!  
From the terminal we see:
~
vaping.plugins.fping sending __init__.py:135
werkzeug 10.0.0.91 - - [14/Mar/2018 11:07:55] "POST /graph_data/ HTTP/1.1" 200 - _internal.py:88
werkzeug 10.0.0.91 - - [14/Mar/2018 11:07:56] "POST /graph_data/ HTTP/1.1" 200 - _internal.py:88
root popen fping -u -C10 -p20 -e 4.2.2.1 208.67.222.222 8.8.8.8 __init__.py:51
werkzeug 10.0.0.91 - - [14/Mar/2018 11:07:57] "POST /graph_data/ HTTP/1.1" 200 - _internal.py:88
root 4.2.2.1        : - - - - - - - - - -
 fping.py:70
root 208.67.222.222 : - - - - - - - - - -
 fping.py:70
root 8.8.8.8        : - - - - - - - - - -
 fping.py:70

fyi, 10.0.0.91 is the virtual box host.

vaping runs without errors. there are a couple interesting messages:
pluginmgr ctor: self._instance={'vodka': <VodkaPlugin at 0x7f8e325a3690>, 'std_fping': <FPing at 0x7f8e325a34b0>} self._class={'vodka': <class 'vaping.plugins.vodka.VodkaPlugin'>, 'fping': <class 'vaping.plugins.fping.FPing'>} config.py:37
2018-03-14 11:07:50,769 - vodka - DEBUG: making sure configuration is sane ...
vodka making sure configuration is sane ... log.py:39
2018-03-14 11:07:50,770 - vodka - WARNING: [config unknown] 'type is not a known configuration variable and has been ignored'
vodka [config unknown] 'type is not a known configuration variable and has been ignored' log.py:66
2018-03-14 11:07:50,771 - vodka - WARNING: [config unknown] 'name is not a known configuration variable and has been ignored'
vodka [config unknown] 'name is not a known configuration variable and has been ignored' log.py:66
2018-03-14 11:07:50,773 - vodka - WARNING: [config deprecated] plugins.http.host is being deprecated in version Well be removed in 2.3.0, it's being replaced by the 'bind' config attribute
vodka [config deprecated] plugins.http.host is being deprecated in version Well be removed in 2.3.0, it's being replaced by the 'bind' config attribute log.py:66
2018-03-14 11:07:50,774 - vodka - WARNING: [config deprecated] plugins.http.port is being deprecated in version Will be removed in 2.3.0, it's being replaced by the 'bind' config attribute
vodka [config deprecated] plugins.http.port is being deprecated in version Will be removed in 2.3.0, it's being replaced by the 'bind' config attribute log.py:66
2018-03-14 11:07:50,775 - vodka - WARNING: [config unknown] 'apps.graphsrv.tmpl_engine is not a known configuration variable and has been ignored'
vodka [config unknown] 'apps.graphsrv.tmpl_engine is not a known configuration variable and has been ignored' log.py:66

$ pip freeze
certifi==2018.1.18
chardet==3.0.4
click==6.7
docutils==0.14
Flask==0.12.2
future==0.16.0
gevent==1.2.2
graphsrv==1.2.0
greenlet==0.4.13
idna==2.6
itsdangerous==0.24
Jinja2==2.10
lockfile==0.12.2
MarkupSafe==1.0
munge==0.5.0
pid==2.2.0
pluginmgr==0.5.0
python-daemon==2.1.2
PyYAML==3.12
requests==2.18.4
twentyc.tmpl==0.2.0
urllib3==1.22
vaping==0.5.0
vodka==2.2.4
Werkzeug==0.14.1
whichcraft==0.4.1

Thank you

**Comment by vegu** [comment]
Does your browser log any javascript errors?

**Comment by vegu** [comment]
Oh actually looks like fping is returning with timeouts ? As such the graph would show those as empty gaps and since there is no data preceeding its just empty

Can you run 

`fping 8.8.8.8 -u -C10 -p20 -e`

outside of vaping and see what that gives you ?

Should be something along the lines of

`8.8.8.8 : 2.97 3.04 3.03 3.12 2.99 3.13 3.04 3.42 3.03 3.26`

**Comment by rrodstein** [comment]
Thank you again for your support!

Looks like a networking issue...
From the vm with vaping:
fping 8.8.8.8 -u -C10 -p20 -e
8.8.8.8 : - - - - - - - - - -
also
fping 4.2.2.1 208.67.222.222 8.8.8.8
4.2.2.1 is unreachable
208.67.222.222 is unreachable
8.8.8.8 is unreachable
$ fping 10.0.0.91 #the host
10.0.0.91 is alive
$ fping 10.0.0.1 #the router
10.0.0.1 is alive

from the virtualbox host:
fping 8.8.8.8 8.8.4.4 104.28.25.20
8.8.8.8 is unreachable
8.8.4.4 is unreachable
104.28.25.20 is unreachable

**Comment by rrodstein** [comment]
My bad, it was our firewall blocking ICMP. Its enabled, and vaping graphs are working like a charm. 

Thank you again for your support!
