### ISSUE TITLE
Unable to run quickstart guide

### ISSUE THREAD

**Issue by oldark87** [20c/vaping#49]
I'm probably missing some incredibly simple here, but I'm following the quickguide steps found https://vaping.readthedocs.io/en/latest/quickstart/ with the modification of using pip3.  (I also tried with just using pip on the python 2 installation just in case).   I see no errors until I get to the last step of 
'Then just start vaping with:

vaping start --home=examples/standalone_dns/ --debug'

At this point I get Command 'vaping' not found, did you mean:....

Is there a configuration or setup step that I am missing here? Thanks in advance.

Edit: Ubuntu 18.04.   No errors other than the one reported in the terminal.

**Comment by oldark87** [comment]
Thanks for the fast response.  I'm installing on the OS level.

Pip freeze:
alabaster==0.7.8
arandr==0.1.9
asn1crypto==0.24.0
attrs==17.4.0
Automat==0.6.0
Babel==2.4.0
backports.functools-lru-cache==1.4
blinker==1.4
certifi==2018.8.24
chardet==3.0.4
Cheetah==2.4.4
Click==7.0
colorama==0.3.7
command-not-found==0.3
configobj==5.0.6
constantly==15.1.0
cryptography==2.1.4
cycler==0.10.0
debtags==2.0
decorator==4.1.2
defer==1.0.6
dirspec==13.10
docutils==0.14
enum34==1.1.6
Flask==0.12.4
future==0.16.0
gevent==1.3.6
GnuPGInterface==0.3.2
gps==3.17
graphsrv==1.4.0
greenlet==0.4.15
httplib2==0.9.2
hyperlink==17.3.1
idna==2.7
imagesize==0.7.1
incremental==16.10.1
ipaddr==2.2.0
ipaddress==1.0.17
itsdangerous==0.24
Jinja2==2.10
keyring==10.6.0
keyrings.alt==3.0
launchpadlib==1.10.6
lazr.restfulclient==0.13.5
lazr.uri==1.0.3
libvirt-python==4.0.0
lockfile==0.12.2
lxml==4.2.1
Mako==1.0.7
MarkupSafe==1.0
matplotlib==2.1.1
mercurial==4.5.3
munge==0.6.0
numpy==1.13.3
oauth==1.0.1
oauthlib==2.0.6
olefile==0.45.1
oneconf==0.3.9
PAM==0.4.2
pexpect==4.2.1
pid==2.2.0
Pillow==5.1.0
piston-mini-client==0.7.5
pluginmgr==0.5.1
psutil==5.4.2
pyasn1==0.4.2
pyasn1-modules==0.2.1
pycairo==1.16.2
pycrypto==2.6.1
pycups==1.9.73
pycurl==7.43.0.1
Pygments==2.2.0
pygobject==3.26.1
PyJWT==1.5.3
PyOpenGL==3.1.0
pyOpenSSL==17.5.0
pyparsing==2.2.0
pyserial==2.6
pysmbc==1.0.15.6
pysqlite==1.0.1
python-apt==1.6.3
python-daemon==2.2.0
python-dateutil==2.6.1
python-debian==0.1.32
pytz==2018.3
pyxdg==0.25
PyYAML==3.13
reportlab==3.4.0
requests==2.19.1
roman==2.0.0
scipy==0.19.1
SecretStorage==2.3.1
service-identity==16.0.0
simplejson==3.13.2
six==1.11.0
software-center-aptd-plugins==0.0.0
Sphinx==1.6.7
sphinx-rtd-theme==0.2.4
subprocess32==3.5.3
twentyc.tmpl==0.2.0
Twisted==17.9.0
typing==3.6.2
urlgrabber==3.10.2
urllib3==1.23
urwid==2.0.1
vaping==1.0.0
virtkey==0.63.0
vodka==2.2.6
wadllib==1.3.2
Werkzeug==0.14.1
whichcraft==0.5.2
wxPython==2.8.12.1
wxPython-common==2.8.12.1
xkit==0.0.0
xlrd==1.1.0
zope.interface==4.3.2

**Comment by vegu** [comment]
i usually install into a virtualenv so i am unsure where the vaping command would end up on an os level install.

you can do `pip  show vaping` to show it's install location, there should be a `vaping` binary somewhere close by. Then just export it to your $PATH env var.

Or alternatively make use of virtualenv if that's an option :)

**Comment by oldark87** [comment]
Wasn't able to locate the binary with a search but I did move the install to a virtual env and that cleared things up. Thanks for the support!
