### ISSUE TITLE
fping.py seems to choke on IPv6 addresses in output

### ISSUE THREAD

**Issue by brocktice** [20c/vaping#50]
root XXXX:XXXX:e800:1::2 : 36.30 36.42 36.26 36.51 36.24 36.63 36.67 36.25 36.19 36.27
 fping.py:68
root failed to get data too many values to unpack fping.py:100
root XXXX:XXXX:f00::1    : 36.87 36.73 36.76 36.82 36.86 36.77 36.71 36.77 36.76 37.56
 fping.py:68
root failed to get data too many values to unpack fping.py:100

**Comment by brocktice** [comment]
AFAICT this is due to the split on colons, doesn't happen with hostnames rather than IPs.

**Comment by grizz** [comment]
Looking into it, thanks.

**Comment by grizz** [comment]
@brocktice No idea how that slipped by testing, thanks for catching it!
