### ISSUE TITLE
Error during install

### ISSUE THREAD

**Issue by fr0zon** [20c/vaping#55]
Hi everyone,
Get this error on Centos7-

Command "/usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-                                    install-KikQ6b/subprocess32/setup.py';f=getattr(tokenize, 'open', open)(__file__                                    );code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'ex                                    ec'))" install --record /tmp/pip-record-EvQYNA/install-record.txt --single-versi                                    on-externally-managed --compile" failed with error code 1 in /tmp/pip-install-Ki                                    kQ6b/subprocess32/

**Comment by vegu** [comment]
@fr0zon never seen before, likely some missing dependency

can you paste the entire output of pip install (assuming there is more)

**Comment by fr0zon** [comment]
@vegu Sure! 

[root@localhost ~]# pip install vaping
Collecting vaping
  Using cached https://files.pythonhosted.org/packages/e0/b0/95026711795901b846d                                                                                                                                                             533f3446bd3971f589132ddd67f27d00d365762ae/vaping-1.1.0.tar.gz
Requirement already satisfied: click>=5.1 in /usr/lib64/python2.7/site-packages                                                                                                                                                              (from vaping) (7.0)
Requirement already satisfied: gevent<3,>=1.1.2 in /usr/lib64/python2.7/site-pac                                                                                                                                                             kages (from vaping) (1.4.0)
Requirement already satisfied: pid<3,>=2.0.1 in /usr/lib/python2.7/site-packages                                                                                                                                                              (from vaping) (2.2.1)
Requirement already satisfied: pluginmgr<0.6,>=0.5.0 in /usr/lib/python2.7/site-                                                                                                                                                             packages (from vaping) (0.5.1)
Requirement already satisfied: python-daemon<3,>=2.1.1 in /usr/lib/python2.7/sit                                                                                                                                                             e-packages (from vaping) (2.2.0)
Requirement already satisfied: munge<1,>=0.6 in /usr/lib/python2.7/site-packages                                                                                                                                                              (from vaping) (0.6.0)
Requirement already satisfied: whichcraft<.5,>=0.4.0 in /usr/lib/python2.7/site-                                                                                                                                                             packages (from vaping) (0.5.2)
Collecting subprocess32<4,>=3.5.2 (from vaping)
  Using cached https://files.pythonhosted.org/packages/be/2b/beeba583e9877e64db1                                                                                                                                                             0b52a96915afc0feabf7144dcbf2a0d0ea68bf73d/subprocess32-3.5.3.tar.gz
Requirement already satisfied: greenlet>=0.4.14; platform_python_implementation                                                                                                                                                              == "CPython" in /usr/lib64/python2.7/site-packages (from gevent<3,>=1.1.2->vapin                                                                                                                                                             g) (0.4.15)
Requirement already satisfied: future<1,>=0.14 in /usr/lib/python2.7/site-packag                                                                                                                                                             es (from pluginmgr<0.6,>=0.5.0->vaping) (0.17.1)
Requirement already satisfied: setuptools in /usr/lib/python2.7/site-packages (f                                                                                                                                                             rom python-daemon<3,>=2.1.1->vaping) (40.6.3)
Requirement already satisfied: lockfile>=0.10 in /usr/lib/python2.7/site-package                                                                                                                                                             s (from python-daemon<3,>=2.1.1->vaping) (0.12.2)
Requirement already satisfied: docutils in /usr/lib/python2.7/site-packages (fro                                                                                                                                                             m python-daemon<3,>=2.1.1->vaping) (0.14)
Requirement already satisfied: PyYAML>=3.10 in /usr/lib64/python2.7/site-package                                                                                                                                                             s (from munge<1,>=0.6->vaping) (3.13)
Requirement already satisfied: requests<3,>=2.6.0 in /usr/lib/python2.7/site-pac                                                                                                                                                             kages (from munge<1,>=0.6->vaping) (2.21.0)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/lib/python2.7/site-                                                                                                                                                             packages (from requests<3,>=2.6.0->munge<1,>=0.6->vaping) (1.24.1)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python2.7/site-                                                                                                                                                             packages (from requests<3,>=2.6.0->munge<1,>=0.6->vaping) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/lib/python2.7/site-package                                                                                                                                                             s (from requests<3,>=2.6.0->munge<1,>=0.6->vaping) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python2.7/site-pac                                                                                                                                                             kages (from requests<3,>=2.6.0->munge<1,>=0.6->vaping) (2018.11.29)
Installing collected packages: subprocess32, vaping
  Running setup.py install for subprocess32 ... error
    Complete output from command /usr/bin/python2 -u -c "import setuptools, toke                                                                                                                                                             nize;__file__='/tmp/pip-install-KikQ6b/subprocess32/setup.py';f=getattr(tokenize                                                                                                                                                             , 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(com                                                                                                                                                             pile(code, __file__, 'exec'))" install --record /tmp/pip-record-EvQYNA/install-r                                                                                                                                                             ecord.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    copying subprocess32.py -> build/lib.linux-x86_64-2.7
    running build_ext
    running build_configure
    checking for gcc... no
    checking for cc... no
    checking for cl.exe... no
    configure: error: in `/tmp/pip-install-KikQ6b/subprocess32':
    configure: error: no acceptable C compiler found in $PATH
    See `config.log' for more details
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-KikQ6b/subprocess32/setup.py", line 120, in <module                                                                                                                                                             >
        main()
      File "/tmp/pip-install-KikQ6b/subprocess32/setup.py", line 114, in main
        'Programming Language :: Python :: Implementation :: CPython',
      File "/usr/lib/python2.7/site-packages/setuptools/__init__.py", line 143,                                                                                                                                                              in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
        dist.run_commands()
      File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", lin                                                                                                                                                             e 61, in run
        return orig.install.run(self)
      File "/usr/lib64/python2.7/distutils/command/install.py", line 563, in run
        self.run_command('build')
      File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib64/python2.7/distutils/command/build.py", line 127, in run
        self.run_command(cmd_name)
      File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-KikQ6b/subprocess32/setup.py", line 41, in run
        self.run_command(command)
      File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-KikQ6b/subprocess32/setup.py", line 26, in run
        raise RuntimeError(configure_command + ' failed.')
    RuntimeError: sh ./configure failed.

    ----------------------------------------
Command "/usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-                                                                                                                                                             install-KikQ6b/subprocess32/setup.py';f=getattr(tokenize, 'open', open)(__file__                                                                                                                                                             );code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'ex                                                                                                                                                             ec'))" install --record /tmp/pip-record-EvQYNA/install-record.txt --single-versi                                                                                                                                                             on-externally-managed --compile" failed with error code 1 in /tmp/pip-install-Ki                                                                                                                                                             kQ6b/subprocess32/

**Comment by vegu** [comment]
looks like it's failing on compiling the subprocess32 module because it can't find a compiler

`yum install gcc`  to install gcc and try again

If it still fails could also try `yum install python-devel`

**Comment by fr0zon** [comment]
It worked ! Thanks Vegu 👍 
i installed gcc and it didnt work then i installed python-devel and it wokred.
