### ISSUE TITLE
Add exporter for Prometheus

### ISSUE THREAD

**Issue by kbreit** [20c/vaping#61]
I would like to see a plugin which allows for exporting data from Vaping to Prometheus. There is a project at https://github.com/bojanrajkovic/vaping-exporter which does this functionality but it would require another container to spin up and additional configuration. A couple of lines in the configuration and Prometheus exporting is enabled would make things easy for users.

**Comment by vegu** [comment]
@kbreit thanks for the feature request, marking this as a possible future enhancement

**Comment by slider143** [comment]
+1

**Comment by grizz** [comment]
Looks like someone already did it - https://github.com/bojanrajkovic/vaping-exporter/blob/master/prometheus.py :)
