### ISSUE TITLE
Documentation is unclear regarding how to use examples

### ISSUE THREAD

**Issue by bandtank** [20c/vaping#82]
The documentation does not make clear how to get started using the examples from the repository. As a first time user, I was confused for a good 20 minutes before I realized I needed to clone the github repository. It may seem obvious to you, but I had no idea what to do and the command line examples referenced a path in the repository without explicitly mentioning anything about the repository. One or two sentences in the installation instructions, quick start guide, or preferably both would have cleared up the confusion immediately.

As an aside, I'm not sure `--home` is a great name for the argument. That was also confusing because I wasn't sure if it was asking for a path to my home directory or a path to the configuration file directory. I don't recall ever using a program that called the configuration directory `home`; regardless, an explanation would have been helpful.

**Comment by bandtank** [comment]
I thought about this some more and it made me wonder why the path is to a directory instead of a file. Is there a reason you have to provide a directory? Would a config file not make more sense?

I think it would be simpler to make `~/.vaping` automatically and then store all configuration files, log files, etc. in there. That would allow the user to use config files with different names instead of needing to name each config file the same way, but in different directories. A single, rotated log file that says which config file is being used would be really helpful.

**Comment by vegu** [comment]
Addressed the documentation issue in 1b4461b 

I will split the other point you raised into a new ticket
