### ISSUE TITLE
Webpage doesn't work in production mode

### ISSUE THREAD

**Issue by bandtank** [20c/vaping#85]
Using the same environment, config file, and command (minus `--debug`) as #84, I am unable to see any output via the same webpage as was accessible in debug mode.

It's running:
```
$ ps -ef | grep `cat vaping.pid`
vapinguser+  348870    1915  0 07:56 ?        00:00:01 ~/.virtualenvs/vaping/bin/python ~/.virtualenvs/vaping/bin/vaping start --home=.
vapinguser+  351046  348870  0 08:10 ?        00:00:00 fping -u -C20 -p500 -e 192.168.4.1 192.168.0.1 205.171.3.65 205.171.2.65 184.99.0.13 8.8.8.8 4.2.2.1 208.67.222.222
```

However, the site isn't working:

![image](https://user-images.githubusercontent.com/1170415/82150635-19562580-9816-11ea-9103-1e166902900d.png)

I don't see anything related to the `vaping` process in `netstat` either:
```
$ netstat -an | grep `cat vaping.pid`
$ grep port config.yml 
        port: 7021
$ netstat -an | grep 7021
```

It doesn't look like the process is writing to any valid files:
```
$ ll /proc/`cat vaping.pid`/fd
```
![image](https://user-images.githubusercontent.com/1170415/82150919-ff691280-9816-11ea-8b37-10ae5151c644.png)

I've been reading the documentation and I don't see anything at all related to production versus development mode in terms of output. If I'm supposed to be looking somewhere else for the output, it is not obvious to me. I don't know where the data is being stored, if there are any log files, or really anything else about the production instance.

**Comment by vegu** [comment]
The output between --debug vs no --debug in terms of the webpage should be the same. Logging  in daemon mode is an issue we still need to address (tracked at #79).

What os are you running on?

**Comment by bandtank** [comment]
This is on Ubuntu 20.04. I assumed the output should be the same, but when the site didn’t work I started questioning the config file and whether or not I missed something during the install. I’m not sure where to look for more information about the instance.

**Comment by grizz** [comment]
That's strange, could you try:

```
netstat -anp | grep `cat vaping.pid`
```

**Comment by bandtank** [comment]
Unfortunately, the result was the same - nothing was found that matches the PID or port. I checked the output manually just to be certain and I did not find anything related to vaping.

**Comment by vegu** [comment]
Able to reproduce this now, looking into it
