### ISSUE TITLE
docker image no longer building

### ISSUE THREAD

**Issue by Kofl** [20c/vaping#89]
The current Dockerfile no longer builds, errors out with (sorry about the formatting):

> Installing build dependencies: finished with status 'error'
> [91m ERROR: Command errored out with exit status 1:

Cloning into '.'...
Warning: Permanently added the RSA host key for IP address '140.82.114.3' to the list of known hosts.
Reset branch 'master'
Your branch is up-to-date with 'origin/master'.
KernelVersion: 4.4.0-1060-aws
Components: [{u'Version': u'19.03.8', u'Name': u'Engine', u'Details': {u'KernelVersion': u'4.4.0-1060-aws', u'Os': u'linux', u'BuildTime': u'2020-03-11T01:24:30.000000000+00:00', u'ApiVersion': u'1.40', u'MinAPIVersion': u'1.12', u'GitCommit': u'afacb8b7f0', u'Arch': u'amd64', u'Experimental': u'false', u'GoVersion': u'go1.12.17'}}, {u'Version': u'1.2.13', u'Name': u'containerd', u'Details': {u'GitCommit': u'7ad184331fa3e55e52b890ea95e65ba581ae3429'}}, {u'Version': u'1.0.0-rc10', u'Name': u'runc', u'Details': {u'GitCommit': u'dc9208a3303feef5b3839f4323d9beb36df0a9dd'}}, {u'Version': u'0.18.0', u'Name': u'docker-init', u'Details': {u'GitCommit': u'fec3683'}}]
Arch: amd64
BuildTime: 2020-03-11T01:24:30.000000000+00:00
ApiVersion: 1.40
Platform: {u'Name': u'Docker Engine - Community'}
Version: 19.03.8
MinAPIVersion: 1.12
GitCommit: afacb8b7f0
Os: linux
GoVersion: go1.12.17
Starting build of index.docker.io/kofl007/vaping:latest...
Step 1/26 : ARG dep_packages="fping"
Step 2/26 : FROM python:3.7-alpine as base
---> 078114edb6be
Step 3/26 : ARG virtual_env=/venv
---> Running in f619c8541cec
Removing intermediate container f619c8541cec
---> 268335a3799e
Step 4/26 : ENV VIRTUAL_ENV="$virtual_env"
---> Running in c846b522e017
Removing intermediate container c846b522e017
---> 08a708dfff6e
Step 5/26 : ENV PATH="$VIRTUAL_ENV/bin:$PATH"
---> Running in 946a5175675a
Removing intermediate container 946a5175675a
---> 419b17d9379b
Step 6/26 : FROM base as builder
---> 419b17d9379b
Step 7/26 : RUN apk --update --no-cache add gcc libc-dev $dep_packages
---> Running in 3d500f47e46e
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
(1/13) Installing libgcc (9.3.0-r2)
(2/13) Installing libstdc++ (9.3.0-r2)
(3/13) Installing binutils (2.34-r1)
(4/13) Installing gmp (6.2.0-r0)
(5/13) Installing isl (0.18-r0)
(6/13) Installing libgomp (9.3.0-r2)
(7/13) Installing libatomic (9.3.0-r2)
(8/13) Installing libgphobos (9.3.0-r2)
(9/13) Installing mpfr4 (4.0.2-r4)
(10/13) Installing mpc1 (1.1.0-r1)
(11/13) Installing gcc (9.3.0-r2)
(12/13) Installing musl-dev (1.1.24-r9)
(13/13) Installing libc-dev (0.7.2-r3)
Executing busybox-1.31.1-r16.trigger
OK: 146 MiB in 48 packages
Removing intermediate container 3d500f47e46e
---> 5f013021f965
Step 8/26 : RUN python3 -m venv "$VIRTUAL_ENV"
---> Running in 7cb3c4c0ff4d
Removing intermediate container 7cb3c4c0ff4d
---> f0c6de4bbdce
Step 9/26 : RUN pip install -U pip pipenv
---> Running in be9c774f98a4
Collecting pip
Downloading pip-20.2.2-py2.py3-none-any.whl (1.5 MB)
Collecting pipenv
Downloading pipenv-2020.8.13-py2.py3-none-any.whl (3.9 MB)
Requirement already satisfied, skipping upgrade: setuptools>=36.2.1 in /venv/lib/python3.7/site-packages (from pipenv) (47.1.0)
Collecting virtualenv
Downloading virtualenv-20.0.31-py2.py3-none-any.whl (4.9 MB)
Collecting virtualenv-clone>=0.2.5
Downloading virtualenv_clone-0.5.4-py2.py3-none-any.whl (6.6 kB)
Collecting certifi
Downloading certifi-2020.6.20-py2.py3-none-any.whl (156 kB)
Collecting six<2,>=1.9.0
Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting distlib<1,>=0.3.1
Downloading distlib-0.3.1-py2.py3-none-any.whl (335 kB)
Collecting appdirs<2,>=1.4.3
Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting filelock<4,>=3.0.0
Downloading filelock-3.0.12-py3-none-any.whl (7.6 kB)
Collecting importlib-metadata<2,>=0.12; python_version < "3.8"
Downloading importlib_metadata-1.7.0-py2.py3-none-any.whl (31 kB)
Collecting zipp>=0.5
Downloading zipp-3.1.0-py3-none-any.whl (4.9 kB)
Installing collected packages: pip, six, distlib, appdirs, filelock, zipp, importlib-metadata, virtualenv, virtualenv-clone, certifi, pipenv
Attempting uninstall: pip
Found existing installation: pip 20.1.1
Uninstalling pip-20.1.1:
Successfully uninstalled pip-20.1.1
Successfully installed appdirs-1.4.4 certifi-2020.6.20 distlib-0.3.1 filelock-3.0.12 importlib-metadata-1.7.0 pip-20.2.2 pipenv-2020.8.13 six-1.15.0 virtualenv-20.0.31 virtualenv-clone-0.5.4 zipp-3.1.0
Removing intermediate container be9c774f98a4
---> 848a88041cb2
Step 10/26 : RUN pip install graphsrv vodka
---> Running in cdaecae509bb
Collecting graphsrv
Downloading graphsrv-1.6.1.tar.gz (195 kB)
Collecting vodka
Downloading vodka-2.3.0.tar.gz (34 kB)
Collecting Jinja2<3.0,>=2.8
Downloading Jinja2-2.11.2-py2.py3-none-any.whl (125 kB)
Collecting Flask<2,>=0.11.1
Downloading Flask-1.1.2-py2.py3-none-any.whl (94 kB)
Collecting munge<1.0.0,>=0.4.0
Downloading munge-0.6.0.tar.gz (12 kB)
Collecting click<8.0,>=6.6
Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting pluginmgr<1,>=0.5.0
Downloading pluginmgr-0.6.0.tar.gz (9.0 kB)
Collecting twentyc.tmpl==0.2.0
Downloading twentyc.tmpl-0.2.0.tar.gz (3.8 kB)
Collecting future<1,>=0.14
Downloading future-0.18.2.tar.gz (829 kB)
Collecting MarkupSafe>=0.23
Downloading MarkupSafe-1.1.1.tar.gz (19 kB)
Collecting itsdangerous>=0.24
Downloading itsdangerous-1.1.0-py2.py3-none-any.whl (16 kB)
Collecting Werkzeug>=0.15
Downloading Werkzeug-1.0.1-py2.py3-none-any.whl (298 kB)
Collecting PyYAML>=3.10
Downloading PyYAML-5.3.1.tar.gz (269 kB)
Collecting requests<3,>=2.6.0
Downloading requests-2.24.0-py2.py3-none-any.whl (61 kB)
Requirement already satisfied: certifi>=2017.4.17 in /venv/lib/python3.7/site-packages (from requests<3,>=2.6.0->munge<1.0.0,>=0.4.0->vodka) (2020.6.20)
Collecting chardet<4,>=3.0.2
Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting idna<3,>=2.5
Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
Downloading urllib3-1.25.10-py2.py3-none-any.whl (127 kB)
Using legacy 'setup.py install' for graphsrv, since package 'wheel' is not installed.
Using legacy 'setup.py install' for vodka, since package 'wheel' is not installed.
Using legacy 'setup.py install' for munge, since package 'wheel' is not installed.
Using legacy 'setup.py install' for pluginmgr, since package 'wheel' is not installed.
Using legacy 'setup.py install' for twentyc.tmpl, since package 'wheel' is not installed.
Using legacy 'setup.py install' for future, since package 'wheel' is not installed.
Using legacy 'setup.py install' for MarkupSafe, since package 'wheel' is not installed.
Using legacy 'setup.py install' for PyYAML, since package 'wheel' is not installed.
Installing collected packages: PyYAML, click, future, chardet, idna, urllib3, requests, munge, pluginmgr, twentyc.tmpl, vodka, MarkupSafe, Jinja2, itsdangerous, Werkzeug, Flask, graphsrv
Running setup.py install for PyYAML: started
Running setup.py install for PyYAML: finished with status 'done'
Running setup.py install for future: started
Running setup.py install for future: finished with status 'done'
Running setup.py install for munge: started
Running setup.py install for munge: finished with status 'done'
Running setup.py install for pluginmgr: started
Running setup.py install for pluginmgr: finished with status 'done'
Running setup.py install for twentyc.tmpl: started
Running setup.py install for twentyc.tmpl: finished with status 'done'
Running setup.py install for vodka: started
Running setup.py install for vodka: finished with status 'done'
Running setup.py install for MarkupSafe: started
Running setup.py install for MarkupSafe: finished with status 'done'
Running setup.py install for graphsrv: started
Running setup.py install for graphsrv: finished with status 'done'
Successfully installed Flask-1.1.2 Jinja2-2.11.2 MarkupSafe-1.1.1 PyYAML-5.3.1 Werkzeug-1.0.1 chardet-3.0.4 click-7.1.2 future-0.18.2 graphsrv-1.6.1 idna-2.10 itsdangerous-1.1.0 munge-0.6.0 pluginmgr-0.6.0 requests-2.24.0 twentyc.tmpl-0.2.0 urllib3-1.25.10 vodka-2.3.0
Removing intermediate container cdaecae509bb
---> 5fdd549cd352
Step 11/26 : WORKDIR /src/vaping
---> Running in 81aaa890203b
Removing intermediate container 81aaa890203b
---> 9bad639123d5
Step 12/26 : ADD . .
---> cdccfb4d54d3
Step 13/26 : RUN pip install .
---> Running in faf904f19dfc
Processing /src/vaping
Requirement already satisfied: click>=5.1 in /venv/lib/python3.7/site-packages (from vaping==1.2.0.1) (7.1.2)
Collecting gevent<3,>=1.1.2
Downloading gevent-1.5.0.tar.gz (5.3 MB)
Installing build dependencies: started
Installing build dependencies: finished with status 'error'
[91m ERROR: Command errored out with exit status 1:
command: /venv/bin/python3 /venv/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-jg1jhtuf/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools >= 40.8.0' wheel 'Cython >= 0.29.14' 'cffi >= 1.12.3 ; platform_python_implementation == '"'"'CPython'"'"'' 'greenlet>=0.4.14 ; platform_python_implementation == '"'"'CPython'"'"''
cwd: None
Complete output (59 lines):
Collecting setuptools>=40.8.0
Downloading setuptools-49.6.0-py3-none-any.whl (803 kB)
Collecting wheel
Downloading wheel-0.35.1-py2.py3-none-any.whl (33 kB)
Collecting Cython>=0.29.14
Downloading Cython-0.29.21-py2.py3-none-any.whl (974 kB)
Collecting cffi>=1.12.3
Downloading cffi-1.14.2.tar.gz (470 kB)
Collecting greenlet>=0.4.14
Downloading greenlet-0.4.16.tar.gz (60 kB)
Collecting pycparser
Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)
Using legacy 'setup.py install' for cffi, since package 'wheel' is not installed.
Using legacy 'setup.py install' for greenlet, since package 'wheel' is not installed.
Installing collected packages: setuptools, wheel, Cython, pycparser, cffi, greenlet
Running setup.py install for cffi: started
Running setup.py install for cffi: finished with status 'error'
ERROR: Command errored out with exit status 1:
command: /venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-grk1mwyy/cffi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-grk1mwyy/cffi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-9ip6dgox/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-jg1jhtuf/overlay --compile --install-headers /tmp/pip-build-env-jg1jhtuf/overlay/include/site/python3.7/cffi
cwd: /tmp/pip-install-grk1mwyy/cffi/
Complete output (36 lines):
running install
running build
running build_py
creating build
creating build/lib.linux-x86_64-3.7
creating build/lib.linux-x86_64-3.7/cffi
copying cffi/pkgconfig.py -> build/lib.linux-x86_64-3.7/cffi
copying cffi/vengine_gen.py -> build/lib.linux-x86_64-3.7/cffi
copying cffi/model.py -> build/lib.linux-x86_64-3.7/cffi
copying cffi/lock.py -> build/lib.linux-x86_64-3.7/cffi
copying cffi/commontypes.py -> build/lib.linux-x86_64-3.7/cffi
copying cffi/setuptools_ext.py -> build/lib.linux-x86_64-3.7/cffi
copying cffi/api.py -> build/lib.linux-x86_64-3.7/cffi
copying cffi/cparser.py -> build/lib.linux-x86_64-3.7/cffi
copying cffi/cffi_opcode.py -> build/lib.linux-x86_64-3.7/cffi
copying cffi/vengine_cpy.py -> build/lib.linux-x86_64-3.7/cffi
copying cffi/verifier.py -> build/lib.linux-x86_64-3.7/cffi
copying cffi/backend_ctypes.py -> build/lib.linux-x86_64-3.7/cffi
copying cffi/__init__.py -> build/lib.linux-x86_64-3.7/cffi
copying cffi/error.py -> build/lib.linux-x86_64-3.7/cffi
copying cffi/recompiler.py -> build/lib.linux-x86_64-3.7/cffi
copying cffi/ffiplatform.py -> build/lib.linux-x86_64-3.7/cffi
copying cffi/_cffi_include.h -> build/lib.linux-x86_64-3.7/cffi
copying cffi/parse_c_type.h -> build/lib.linux-x86_64-3.7/cffi
copying cffi/_embedding.h -> build/lib.linux-x86_64-3.7/cffi
copying cffi/_cffi_errors.h -> build/lib.linux-x86_64-3.7/cffi
running build_ext
building '_cffi_backend' extension
creating build/temp.linux-x86_64-3.7
creating build/temp.linux-x86_64-3.7/c
gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/venv/include -I/usr/local/include/python3.7m -c c/_cffi_backend.c -o build/temp.linux-x86_64-3.7/c/_cffi_backend.o
c/_cffi_backend.c:15:10: fatal error: ffi.h: No such file or directory
15 | #include <ffi.h>
| ^~~~~~~
compilation terminated.
error: command 'gcc' failed with exit status 1
----------------------------------------
ERROR: Command errored out with exit status 1: /venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-grk1mwyy/cffi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-grk1mwyy/cffi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-9ip6dgox/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-jg1jhtuf/overlay --compile --install-headers /tmp/pip-build-env-jg1jhtuf/overlay/include/site/python3.7/cffi Check the logs for full command output.
----------------------------------------
[0m
[91mERROR: Command errored out with exit status 1: /venv/bin/python3 /venv/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-jg1jhtuf/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools >= 40.8.0' wheel 'Cython >= 0.29.14' 'cffi >= 1.12.3 ; platform_python_implementation == '"'"'CPython'"'"'' 'greenlet>=0.4.14 ; platform_python_implementation == '"'"'CPython'"'"'' Check the logs for full command output.
[0m
Removing intermediate container faf904f19dfc
The command '/bin/sh -c pip install .' returned a non-zero code: 1

**Comment by vegu** [comment]
Pull request has been merged and fix will be rolled out with the next release, thanks for the bug report and testing of the PR, closing this ticket :)
