### ISSUE TITLE
pip/pypi pacakge is outdated?

### ISSUE THREAD

**Issue by justinc1** [20c/vaping#9]
Installed via pip, and got error:
```
(vaping)justin_cinkelj@jcdell .vaping $ vaping --debug star
...
  File "/home/justin_cinkelj/.virtualenvs/vaping/lib/python3.5/site-packages/vaping/__init__.py", line 3, in <module>
    from config import Config # noqa
ImportError: No module named 'config'
```

So the . in front on config is missing. But it is there in github source. So the pypi package seems to be outdated.

**Comment by FlorianHeigl** [comment]
Just had the same issue, the pip version will install, but if you pip install config you end up with a version of _config_ that is not ready for python3, and now you have many more issues than you had ever wanted.

**Comment by grizz** [comment]
Released py3 version here: https://pypi.python.org/pypi/vaping/0.3.0
